version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_portfolio
    volumes:
      - .:/app
    ports:
      - "8001:8000"  # Changed to 8001 to avoid conflicts
    networks:
      - existing_network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=server
      - MYSQL_PASSWORD=4734
      - MYSQL_DATABASE=u614166417_nil_port

networks:
  existing_network:
    external: true
    name: app-network
