# Generated by Django 5.1.4 on 2024-12-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='education_images/')),
                ('nom_ecole', models.CharField(max_length=255)),
                ('nom_parcours', models.CharField(max_length=255)),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('lieu', models.CharField(max_length=255)),
            ],
        ),
    ]
