# Generated by Django 5.1.4 on 2024-12-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('techno', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(related_name='related_projets', to='core.imageprojet')),
            ],
        ),
        migrations.AddField(
            model_name='imageprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='core.projet'),
        ),
    ]
