# Generated by Django 5.1.4 on 2024-12-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('email_entreprise', models.EmailField(max_length=254)),
                ('lieu_entreprise', models.CharField(max_length=255)),
                ('date_envoi', models.DateField(auto_now_add=True)),
                ('heure_envoi', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
