# Generated by Django 5.1.4 on 2025-01-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
            ],
        ),
    ]
