# Generated by Django 5.1.4 on 2025-01-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_langue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='competences/images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('niveau', models.IntegerField()),
            ],
        ),
    ]
