# Generated by Django 5.1.4 on 2025-01-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_competence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='images',
        ),
    ]
