# Generated by Django 5.1.4 on 2025-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_projet_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('formateur', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
    ]
