# Generated by Django 5.1.4 on 2025-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notation'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='heure',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='heure',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
