# Generated by Django 5.1.4 on 2025-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_email_date_email_heure_emailresponse_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
            ],
        ),
    ]
