# Generated by Django 5.1.4 on 2025-01-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
