# Generated by Django 5.1.4 on 2025-01-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_link_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
