# Generated by Django 5.1.4 on 2025-01-30 19:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='competence',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='competences/images/', validators=[core.models.validate_svg]),
        ),
    ]
