# Generated by Django 5.1.4 on 2025-01-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_facebook_alter_competence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
