# Generated by Django 5.1.4 on 2025-01-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_facebook_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='githublink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='projetlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
