# Generated by Django 5.1.4 on 2025-05-03 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20250131_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='competences/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
