# Generated by Django 5.1.4 on 2026-03-14 07:19

from django.db import migrations


def load_default_message_templates(apps, schema_editor):
    """Load default FR/EN message templates for prospecting"""
    MessageTemplate = apps.get_model('core', 'MessageTemplate')
    
    templates = [
        # Initial Contact - FR
        {
            'name': 'Premier contact',
            'language': 'fr',
            'stage': 'initial',
            'subject': 'Création de site web pour {company_name}',
            'body': '''Bonjour {contact_name},

Je suis développeur web et je crée des sites internet pour les entreprises locales.

J'ai remarqué que {company_name} n'a pas encore de site web.
Un site pourrait permettre à vos clients de voir vos services, vos horaires et vous trouver facilement sur internet.

Si vous voulez, je peux vous montrer un exemple de site que je pourrais créer pour vous.

Cordialement,''',
            'is_default': True
        },
        # Initial Contact - EN
        {
            'name': 'First Contact',
            'language': 'en',
            'stage': 'initial',
            'subject': 'Website creation for {company_name}',
            'body': '''Hello {contact_name},

I'm a web developer creating websites for local businesses.

I noticed that {company_name} doesn't have a website yet.
A website could help your customers see your services, hours, and find you easily online.

If you'd like, I can show you an example of a website I could create for you.

Best regards,''',
            'is_default': True
        },
        # Follow Up - FR
        {
            'name': 'Relance',
            'language': 'fr',
            'stage': 'follow_up',
            'subject': 'Relance - Site web pour {company_name}',
            'body': '''Bonjour {contact_name},

Je fais suite à mon dernier message concernant la création d'un site web pour {company_name}.

Avez-vous eu le temps de réfléchir à ma proposition ?
Je serais ravi d'en discuter avec vous.

Cordialement,''',
            'is_default': True
        },
        # Follow Up - EN
        {
            'name': 'Follow Up',
            'language': 'en',
            'stage': 'follow_up',
            'subject': 'Follow Up - Website for {company_name}',
            'body': '''Hello {contact_name},

I'm following up on my previous message about creating a website for {company_name}.

Have you had time to consider my proposal?
I'd be happy to discuss it with you.

Best regards,''',
            'is_default': True
        },
        # Proposal - FR
        {
            'name': 'Proposition commerciale',
            'language': 'fr',
            'stage': 'proposal',
            'subject': 'Proposition commerciale - Site web {company_name}',
            'body': '''Bonjour {contact_name},

Suite à notre échange, voici ma proposition pour votre site web :

✅ Design personnalisé
✅ Mise en ligne
✅ Optimisation mobile
✅ Référencement Google

Prix : {estimated_value} €

Si cette proposition vous convient, nous pouvons commencer cette semaine.

Cordialement,''',
            'is_default': True
        },
        # Proposal - EN
        {
            'name': 'Business Proposal',
            'language': 'en',
            'stage': 'proposal',
            'subject': 'Business Proposal - Website for {company_name}',
            'body': '''Hello {contact_name},

Following our conversation, here's my proposal for your website:

✅ Custom design
✅ Online deployment
✅ Mobile optimization
✅ Google SEO

Price: {estimated_value} €

If this proposal works for you, we can start this week.

Best regards,''',
            'is_default': True
        },
        # Closing - FR
        {
            'name': 'Confirmation',
            'language': 'fr',
            'stage': 'closing',
            'subject': 'Confirmation - Projet site web {company_name}',
            'body': '''Bonjour {contact_name},

Je vous confirme que nous pouvons commencer la création de votre site web.

Pour démarrer, j'aurai besoin de :
- Votre logo
- Quelques photos
- Vos textes de présentation

N'hésitez pas si vous avez des questions.

Cordialement,''',
            'is_default': True
        },
        # Closing - EN
        {
            'name': 'Confirmation',
            'language': 'en',
            'stage': 'closing',
            'subject': 'Confirmation - Website project for {company_name}',
            'body': '''Hello {contact_name},

I confirm that we can start creating your website.

To begin, I'll need:
- Your logo
- Some photos
- Your presentation texts

Feel free to ask if you have any questions.

Best regards,''',
            'is_default': True
        },
    ]
    
    for t in templates:
        obj, created = MessageTemplate.objects.get_or_create(
            name=t['name'],
            language=t['language'],
            stage=t['stage'],
            defaults=t
        )
        if created:
            print(f"Created template: {t['name']} ({t['language']})")


def unload_default_message_templates(apps, schema_editor):
    """Remove default templates (for rollback)"""
    MessageTemplate = apps.get_model('core', 'MessageTemplate')
    MessageTemplate.objects.filter(
        name__in=['Premier contact', 'First Contact', 'Relance', 'Follow Up', 
                  'Proposition commerciale', 'Business Proposal', 'Confirmation']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_messagetemplate_prospect_prospectmessage_and_more'),
    ]

    operations = [
        migrations.RunPython(load_default_message_templates, unload_default_message_templates),
    ]
