# Generated by Django 5.1.4 on 2026-03-14 07:57

from django.db import migrations, models


def load_internship_templates(apps, schema_editor):
    """Load default internship message templates"""
    MessageTemplate = apps.get_model('core', 'MessageTemplate')
    
    internship_templates = [
        {
            'name': 'Candidature Stage Dev Web',
            'language': 'fr',
            'stage': 'initial',
            'usage_type': 'internship',
            'subject': 'Candidature spontanée pour un stage en développement web',
            'body': '''Madame, Monsieur,\n\nActuellement étudiant en 3ème année de Licence en Informatique à l'ENI, je suis à la recherche d'un stage professionnel d'une durée de {internship_duration} à partir du {internship_start_date}.\n\nVotre entreprise {company_name} représente pour moi une opportunité exceptionnelle de développer mes compétences en développement web Django et en administration systèmes et réseaux.\n\nMotivé, sérieux et autonome, je serais honoré de pouvoir contribuer au développement de vos projets informatiques.\n\nJe reste à votre disposition pour un entretien.\n\nCordialement,\n{student_name}''',
            'cover_letter_html': '''<!DOCTYPE html>\n<html lang="fr">\n<head>\n    <meta charset="UTF-8">\n    <style>\n        @page { margin: 2cm; }\n        body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.6; }\n        .header { text-align: center; margin-bottom: 30px; }\n        .student-info { text-align: left; margin-bottom: 20px; }\n        .company-info { text-align: left; margin-top: 30px; }\n        .subject { font-weight: bold; margin: 20px 0; }\n        .content { text-align: justify; }\n        .signature { margin-top: 40px; }\n    </style>\n</head>\n<body>\n    <div class="header">\n        <h2>Lettre de Motivation</h2>\n        <p>Demande de stage en {{ internship_type }}</p>\n    </div>\n    \n    <div class="student-info">\n        <strong>{{ student_name }}</strong><br>\n        {{ email }}<br>\n        {{ phone }}<br>\n        Étudiant à {{ school_name }}\n    </div>\n    \n    <div class="company-info">\n        À l'attention de {{ contact_name }}<br>\n        {{ company_name }}<br>\n        {{ city }}\n    </div>\n    \n    <div class="subject">\n        Objet : Candidature pour un stage de {{ internship_duration }} à partir du {{ internship_start_date }}\n    </div>\n    \n    <div class="content">\n        <p>Madame, Monsieur,</p>\n        \n        <p>Actuellement étudiant en 3ème année de Licence en Informatique à {{ school_name }}, je suis à la recherche d'un stage professionnel.</p>\n        \n        <p>Votre entreprise {{ company_name }} représente une opportunité exceptionnelle.</p>\n        \n        <p>Motivé, sérieux et autonome, je serais honoré de contribuer à vos projets.</p>\n        \n        <p>Cordialement,</p>\n    </div>\n    \n    <div class="signature">\n        <p>{{ student_name }}</p>\n    </div>\n</body>\n</html>''',
            'is_default': True
        },
        {
            'name': 'Internship Application Web Dev',
            'language': 'en',
            'stage': 'initial',
            'usage_type': 'internship',
            'subject': 'Internship application - Web Development',
            'body': '''Dear Sir/Madam,\n\nCurrently a 3rd year Computer Science student at ENI, I am looking for a professional internship of {internship_duration} starting from {internship_start_date}.\n\nYour company {company_name} represents an exceptional opportunity to develop my skills in Django web development.\n\nMotivated, serious and autonomous, I would be honored to contribute to your IT projects.\n\nBest regards,\n{student_name}''',
            'cover_letter_html': '''<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <style>\n        @page { margin: 2cm; }\n        body { font-family: Arial, sans-serif; font-size: 12pt; line-height: 1.6; }\n    </style>\n</head>\n<body>\n    <h2>Cover Letter</h2>\n    <p>{{ student_name }}</p>\n    <p>{{ company_name }}</p>\n</body>\n</html>''',
            'is_default': True
        },
        {
            'name': 'Relance Stage',
            'language': 'fr',
            'stage': 'follow_up',
            'usage_type': 'internship',
            'subject': 'Relance - Candidature stage',
            'body': '''Madame, Monsieur,\n\nJe me permets de vous relancer concernant ma candidature pour un stage au sein de {company_name}.\n\nJe reste très motivé à l'idée de rejoindre votre équipe.\n\nCordialement,\n{student_name}''',
            'cover_letter_html': '',
            'is_default': True
        },
        {
            'name': 'Internship Follow Up',
            'language': 'en',
            'stage': 'follow_up',
            'usage_type': 'internship',
            'subject': 'Follow Up - Internship Application',
            'body': '''Dear Sir/Madam,\n\nI am writing to follow up on my internship application at {company_name}.\n\nI remain very motivated to join your team.\n\nBest regards,\n{student_name}''',
            'cover_letter_html': '',
            'is_default': True
        },
        {
            'name': 'Remerciements Entretien',
            'language': 'fr',
            'stage': 'thank_you',
            'usage_type': 'internship',
            'subject': 'Remerciements suite à notre entretien',
            'body': '''Madame, Monsieur,\n\nJe tiens à vous remercier pour le temps accordé lors de notre entretien.\n\nNotre échange a confirmé mon vif intérêt pour {company_name}.\n\nCordialement,\n{student_name}''',
            'cover_letter_html': '',
            'is_default': True
        },
        {
            'name': 'Interview Thank You',
            'language': 'en',
            'stage': 'thank_you',
            'usage_type': 'internship',
            'subject': 'Thank You - Interview',
            'body': '''Dear Sir/Madam,\n\nThank you for taking the time to meet with me.\n\nOur conversation confirmed my interest in {company_name}.\n\nBest regards,\n{student_name}''',
            'cover_letter_html': '',
            'is_default': True
        },
        {
            'name': 'Acceptation Stage',
            'language': 'fr',
            'stage': 'acceptance',
            'usage_type': 'internship',
            'subject': "Acceptation de l'offre de stage",
            'body': '''Madame, Monsieur,\n\nJe suis très heureux de confirmer mon acceptation de l'offre de stage au sein de {company_name}.\n\nCordialement,\n{student_name}''',
            'cover_letter_html': '',
            'is_default': True
        },
        {
            'name': 'Internship Acceptance',
            'language': 'en',
            'stage': 'acceptance',
            'usage_type': 'internship',
            'subject': 'Acceptance of Internship Offer',
            'body': '''Dear Sir/Madam,\n\nI am pleased to confirm my acceptance of the internship offer at {company_name}.\n\nBest regards,\n{student_name}''',
            'cover_letter_html': '',
            'is_default': True
        },
    ]
    
    for t in internship_templates:
        obj, created = MessageTemplate.objects.get_or_create(
            name=t['name'],
            language=t['language'],
            stage=t['stage'],
            usage_type=t['usage_type'],
            defaults=t
        )
        if created:
            print(f"Created template: {t['name']} ({t['language']})")


def unload_internship_templates(apps, schema_editor):
    """Remove internship templates (for rollback)"""
    MessageTemplate = apps.get_model('core', 'MessageTemplate')
    MessageTemplate.objects.filter(usage_type='internship').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20260314_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['usage_type', 'stage', 'language', 'name'], 'verbose_name': 'Message Template', 'verbose_name_plural': 'Message Templates'},
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='cover_letter_html',
            field=models.TextField(blank=True, help_text='HTML template for PDF generation (internship only)'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='usage_type',
            field=models.CharField(choices=[('prospecting', 'Prospecting (Sales)'), ('internship', 'Internship Request')], default='prospecting', max_length=20),
        ),
        migrations.RunPython(load_internship_templates, unload_internship_templates),
    ]
