# Generated by Django 5.1.4 on 2026-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_messagetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL Page Facebook ou profil'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp (avec indicatif, ex: +261...)', max_length=20),
        ),
        migrations.AddField(
            model_name='prospectmessage',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook Messenger')], default='email', max_length=20),
        ),
    ]
