# Generated by Django 5.1.4 on 2026-03-16 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_prospect_facebook_url_prospect_whatsapp_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment about this rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.prospect')),
            ],
            options={
                'verbose_name': 'Prospect Rating',
                'verbose_name_plural': 'Prospect Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('prospect',)},
            },
        ),
    ]
