# Generated by Django 5.1.4 on 2026-03-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_prospectrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attached file paths (for email channel only)', null=True),
        ),
    ]
