# Generated by Django 5.1.4 on 2026-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_prospectmessage_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='prospect_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Prospect Attachment',
                'verbose_name_plural': 'Prospect Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='prospectmessage',
            name='attachments',
        ),
        migrations.AddField(
            model_name='prospectmessage',
            name='attachment_files',
            field=models.JSONField(blank=True, default=list, help_text='List of attached file URLs stored in media/ (for email channel only)', null=True),
        ),
    ]
