# Generated by Django 5.1.4 on 2026-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_prospectattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectmessage',
            name='include_cv',
            field=models.BooleanField(default=False, help_text='Automatically attach CV from database (for email channel only)'),
        ),
    ]
