# Generated by Django 5.1.4 on 2026-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_webauthn_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='aaguid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hex digest du credential_id (auto-généré à la création)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='device_name',
            field=models.CharField(default='Face ID / Biometric', max_length=255),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
