version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile  # Utiliser ton Dockerfile existant pour construire l'image MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 4734
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: server
      MYSQL_PASSWORD: 4734
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 4734
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
